create S3 bucket, S3 object, DynamoDB Table, and Remote S3 Backend
mleager/AWS-VPC-and-Terraform pull request #6
Opened 2023-07-28 22:49 UTC by mleager

2023-07-28 23:40 UTC, mleager commented
remember to properly format syntax ( "terraform fmt" )

2023-07-29 15:53 UTC, geoffrey1330 requested changes

2023-07-29 15:53 UTC, geoffrey1330 commented on terraform.tf
> +    dynamodb_table = "tf-remote-state-locking"
could you please format your code by running `terraform fmt`

2023-07-29 16:00 UTC, geoffrey1330 approved these changes

2023-07-29 16:01 UTC, merged